baseURL = "/"
languageCode = "en"
title = "randomsecurity.dev"
theme = "hugo-coder"
defaultcontentlanguage = "en"
paginate = 6
enableEmoji = true


[params]
author = "The Random Security Guy"
description = "Father | Ultra Runner | Advisor | Innovator | Security @ Eagle Eye Networks"
info = "Father | Ultra Runner | Advisor | Innovator | Security @ Eagle Eye Networks"
keywords = "blog,developer,personal,security"
avatarURL = "images/dc-01.png"
dateFormat = "January 2, 2006"
since = 2019
customCss = []
rtl = false
commit = "https://github.com/luizdepra/hugo-coder/tree/"
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/therandomsecurityguy/"

[[params.social]]
name = "Mastodon"
icon = "fa fa-2x fa-mastodon"
weight = 3
url = "https://infosec.exchange/@randomsec"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/dchamorro/"

[[params.social]]
name = "Publications"
icon = "fa fa-2x fa-book"
weight = 5
url = "https://scholar.google.com/citations?user=s08AV6UAAAAJ&hl=en"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 6
url = "/posts/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Research"
weight = 3
url = "research/"
#[[languages.en.menu.main]]
#name = "Contact me"
#weight = 5
#url = "contact/"
